Revert back to core-ktx 1.1.0
kau.Dependencies.coreKtx is causing a fatal exception on
startup.

E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.pitchedapps.frost, PID: 7273
E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setCornerRadius(F)V
in class Lf/c/a/b/a0/k; or its super classes (declaration of 'f.c.a.b.a0.k' appears
in /data/app/com.pitchedapps.frost-1/base.apk)